sudo: required
language: python
python:
- '3.6'
addons:
  sonarcloud:
    organization: awt03
    token:
      secure: "$SONAR_TOKEN"
install:
- pip3 install -r requirements.txt
before_install:
- openssl aes-256-cbc -K $encrypted_b8b517d445f7_key -iv $encrypted_b8b517d445f7_iv
  -in pivotal_tracker/config.json.enc -out pivotal_tracker/config.json -d
script:
- sonar-scanner
- behave pivotal_tracker/features --tags=~@wip
notifications:
  email: true
