sudo: required
language: python
python:
- '3.6'
addons:
  chrome: stable
  sonarcloud:
    organization: awt03
    token:
      secure: "$SONAR_TOKEN"
install:
- pip3 install -r requirements.txt
before_install:
- openssl aes-256-cbc -K $encrypted_2ca06f9666ee_key -iv $encrypted_2ca06f9666ee_iv
  -in pivotal_tracker/config.json.enc -out pivotal_tracker/config.json -d
script:
- sonar-scanner
- behave pivotal_tracker/api/features --tags=~@wip --tags=~@defect
- behave pivotal_tracker/ui/features --tags=~@wip --tags=~@defect
notifications:
  email: true
env:
  global:
    secure: KEmLtqHQduNWR34rh74R05KZYZjYMccNv4Y589KxHelEIJekJVS4aE19iAYFdcpLPLJS1syb6OfQqkjxvsdZ86Y6Rbr043aWNEoOuQVM0SJcpnigtnHAmR55vBOWUE4KFtPeR8W7VTBRoz3l19KKH+gNAGXii5xNVYBOw0xTBpthhjK4tYBTzJ6bm5rAqhRCRVVyeqLGuywis38HcQ7zUAzv+JqKkW2qG3UukZfKFAG63jB8/7WkfA5r5DHGNDYQ+jdLKuN3xnMgUz1D3DzfnmChVUtwl0Oc43L6DJNZ2RduqTwlo8He6v363RwMIZlWGRyu7guq25s4QpzgjM7Ph5mDk4crVQXI9kTAtF9QnO9n5Ra/mmb82hYOVitT071YGRop9Bq+hQc5aSzPdYopcXrpzghPE8On61hr/tzsg8JO8HeuUfi/I4NHueCxsK3KmVuKIqWQiduP78XNL49Pf5Wv/ZW38WrfkGUXvWD3XYmB4cJweBRvjdrMFk3LU5pLkh/N4bAoz79k+JKkT83ajRqgO3iQcplVNbLDOxErtIpouvkOOFWJtHLK0418xz4iB6XMfuGyoZ8vyK7XIcwJpzbYSn3wZMGxFPHjypAYaPG+SoEyYZGwnn2Yi4s7RTBvBjQnkYOl7crUHICLl4n5/MRy8S4AheLPj6WCZwZfqkE=
