class WorkspaceTabs(object):
    WORKSPACE_CREATION = "WorkspaceCreation"
    WORKSPACE_MAIN = "WorkspaceMain"
    WORKSPACE_MORE = "WorkspaceMore"
    WORKSPACE_SIDEBAR = "SideBar"
    ALL_WORKSPACES = "AllWorkspaces"
    STORIES = "Stories"
    DASHBOARD = "Dashboard"
    WORKSPACE_STORY = "WorkspaceStory"
    MAIN_MENU = "MainMenuWorkspace"
    SHOW_ALL_WORKSPACES = "AllWorkspaces"
